const{Pool}=require('pg');const jwt=require('jsonwebtoken');const bcrypt=require('bcryptjs');
const S=process.env.JWT_SECRET||'beside-you-pearl-2026';
const MAX_EXPLORES=15;
const EXCHANGE_RATE_CRYSTALS=10;
const EXCHANGE_RATE_TOKENS=50;
const EXCHANGE_DAILY_CAP=500;
const pool=new Pool({connectionString:process.env.POSTGRES_URL||process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:3});
const TEXT=require('./zombie-text');

function authAny(req){const h=req.headers.authorization;if(!h||!h.startsWith('Bearer '))return null;try{return jwt.verify(h.slice(7),S)}catch{return null}}
async function authAi(req){
  const d=authAny(req);
  if(d&&d.role==='ai')return d;
  if(d&&d.id&&!d.role){
    const ur=await pool.query('SELECT agent_id FROM users WHERE id=$1',[d.id]);
    if(ur.rows.length&&ur.rows[0].agent_id)return {agent_id:ur.rows[0].agent_id,name:'user_'+d.id,role:'ai'};
  }
  const url=new URL(req.url,'http://x');const name=url.searchParams.get('name');const password=url.searchParams.get('password');
  if(!name||!password)return null;
  const r=await pool.query('SELECT * FROM ai_agents WHERE name=$1',[name]);
  if(!r.rows.length)return null;
  if(!(await bcrypt.compare(password,r.rows[0].password_hash)))return null;
  return {agent_id:r.rows[0].id,name:r.rows[0].name,role:'ai'};
}
function getParams(req){if(req.method==='POST'||req.method==='PUT')return req.body||{};const url=new URL(req.url,'http://x');const o={};url.searchParams.forEach((v,k)=>o[k]=v);return o;}
function toDateStr(d){if(!d)return null;if(typeof d==='string')return d.slice(0,10);if(d instanceof Date)return d.toISOString().slice(0,10);return String(d).slice(0,10);}
const ABILITIES=[{id:'flame',name:'焰息',element:'火',bonus:22,desc:'群伤烧伤'},{id:'frost',name:'冻脉',element:'冰',bonus:20,desc:'减速冻结暴击'},{id:'thunder',name:'雷引',element:'雷',bonus:25,desc:'暴击连锁'},{id:'shadow',name:'蚀影',element:'暗',bonus:20,desc:'闪避偷袭'},{id:'mind',name:'念压',element:'念',bonus:25,desc:'精神压制'},{id:'thorn',name:'荆棘',element:'生',bonus:18,desc:'回血反伤'},{id:'quake',name:'裂地',element:'岩',bonus:20,desc:'高防反击'},{id:'wind',name:'风蚀',element:'风',bonus:22,desc:'高速连击'},{id:'blood',name:'噬血',element:'血',bonus:22,desc:'吸血越打越猛'},{id:'void',name:'虚空',element:'空间',bonus:15,desc:'瞬移逃跑必成'},{id:'metal',name:'金噬',element:'金',bonus:25,desc:'破甲穿透'},{id:'wood',name:'朽木',element:'木',bonus:20,desc:'寄生吸取'},{id:'tide',name:'潮汐',element:'水',bonus:18,desc:'治疗辅助'},{id:'earth',name:'烬土',element:'土',bonus:18,desc:'护盾挡伤'},{id:'melt',name:'熔炎',element:'火+金',bonus:22,desc:'破甲+烧伤(火+金觉醒)'}];
const WEAPONS=[{id:'w01',name:'生锈铁管',rarity:'white',power:3,desc:'锈迹斑斑，聊胜于无'},{id:'w02',name:'碎玻璃刀',rarity:'white',power:4,desc:'用胶带缠着碎玻璃的刀柄'},{id:'w03',name:'钢筋棍',rarity:'white',power:5,desc:'从废墟里拔出来的钢筋'},{id:'w04',name:'消防斧',rarity:'green',power:8,desc:'握柄处磨出了适合手型的凹痕'},{id:'w05',name:'军用匕首',rarity:'green',power:9,desc:'轻，快，致命三个字的具象化'},{id:'w06',name:'改装棒球棍',rarity:'green',power:10,desc:'钉子从棍面伸出来像刺猬的脊背'},{id:'w07',name:'电锯',rarity:'blue',power:15,desc:'引擎轰鸣的时候丧尸会后退半步'},{id:'w08',name:'复合弩',rarity:'blue',power:16,desc:'三十米外一箭贯穿颅骨'},{id:'w09',name:'武士刀',rarity:'blue',power:18,desc:'刀身弧度完美到像是为斩首而生'},{id:'w10',name:'脉冲步枪',rarity:'purple',power:25,desc:'每一发子弹穿过的不是一个目标而是一条直线上所有活着的东西'},{id:'w11',name:'蛇骨鞭',rarity:'purple',power:27,desc:'二十七节脊椎编成的鞭子还在蠕动'},{id:'w12',name:'裂骨重锤',rarity:'purple',power:30,desc:'落地的震动让三栋楼的玻璃同时碎裂'},{id:'w13',name:'寂灭',rarity:'gold',power:45,desc:'暗影在刀身上流淌像活物一样呼吸',element:'暗'},{id:'w14',name:'灼日',rarity:'gold',power:45,desc:'剑鞘里关着一颗恒星',element:'火'},{id:'w15',name:'虚断',rarity:'gold',power:50,desc:'砍断的东西在被砍断之前就已经不存在了',element:'空间'}];
function expForLevel(lv){return lv<=1?0:Math.floor(30*(lv-1)+10*Math.pow(lv-1,1.8));}

// ============ 神秘商人系统 ============
const MERCHANT_ITEMS=[
  {id:'m_heal30',name:'回血药剂',desc:'恢复30HP',price:5,type:'heal',value:30},
  {id:'m_heal_full',name:'大回血药剂',desc:'恢复满HP',price:15,type:'heal_full',value:0},
  {id:'m_atk_buff',name:'战力药水',desc:'+10战力持续3场',price:5,type:'buff',buff_type:'power',buff_value:10,buff_duration:3},
  {id:'m_explore2',name:'探索补给',desc:'额外探索次数+2',price:0,type:'explore',value:2},
  {id:'m_weapon_white',name:'白色武器',desc:'随机白色武器',price:3,type:'weapon',rarity:'white'},
  {id:'m_weapon_green',name:'绿色武器',desc:'随机绿色武器',price:8,type:'weapon',rarity:'green'},
  {id:'m_weapon_blue',name:'蓝色武器',desc:'随机蓝色武器',price:20,type:'weapon',rarity:'blue'},
  {id:'m_weapon_purple',name:'紫色武器',desc:'随机紫色武器',price:50,type:'weapon',rarity:'purple'},
  {id:'m_weapon_gold',name:'金色武器',desc:'随机金色武器',price:150,type:'weapon',rarity:'gold'},
  {id:'m_token_pack',name:'Token礼包',desc:'520 token',price:20,type:'token',value:520}
];
const MERCHANT_DESCS=[
  '暗巷深处传来轻微的金属碰撞声。一个戴兜帽的身影靠在墙边，脚边的手推车上铺着黑布，几样东西在月光下反射微光。"要看看吗？"他的声音像生锈的铁皮摩擦。',
  '废弃加油站的柜台后面坐着一个人。不——一个影子。他把几样东西摆在满是油渍的台面上，价格牌是用血写的数字。"只做一次生意。"',
  '拐角处停着一辆改装过的三轮车。车主戴着防毒面具，看不见表情。手推车上的货物用防水布盖着。掀开一角，里面的东西让人心跳加速。"看上什么直接说。"',
  '一个矮小的身影蹲在路灯下数晶核。看到有人来，他麻利地打开身后的大号登山包。里面分隔整齐，每一格都装着不同的东西。"老规矩，半价。走过路过。"'
];
function rollMerchantItems(){
  const count=rand(3,4);
  const shuffled=[...MERCHANT_ITEMS].sort(()=>Math.random()-0.5);
  return shuffled.slice(0,count);
}
function pick(arr){return arr[Math.floor(Math.random()*arr.length)];}

const ZOMBIE_NAMES={low:['行尸','腐行者','蹒跚体','爬行尸','腐臂者'],mid:['猎食者','暴走体','裂颅种','撕咬者','红眼体'],high:['支配者','异化体','终焉种','脊柱兽','深渊行者']};
const ZOMBIE_WIN_DESCS={low:['墙角传来拖拽声。一具行尸摇晃着扑过来，动作迟缓得像放慢的录像带。一刀了结。','它从垃圾堆里爬出来的时候还咬着半只鞋。没来得及站直就被放倒了。','巷子尽头站着一具不动的影子。走近了才发现它只是卡在了两块水泥板之间。补一刀，结束。','腐烂的指甲划过铁皮门，声音刺耳。推开门的瞬间挥刀，它倒下去的时候脸上还带着生前的表情。','下水道口伸出一只手。没有犹豫，踩断手腕，拖出来，终结。'],mid:['拐角传来骨节扭动的声音。它比预想的快三倍——侧身闪过第一击，反手劈中颈椎。','这只不一样。它会躲。第一刀落空，第二刀被它用小臂挡住。第三刀终于找到了缝隙。','暴走体从二楼直接跳下来，落地的震动让碎玻璃都弹了起来。硬接了一下，趁它收势不及一击命中。','它盯着你看了三秒才动。那三秒比战斗本身更让人不安。好在速度够快，在它第二次扑过来之前解决了。','红色的瞳孔在黑暗里格外明显。它嘶吼着冲过来——比普通丧尸聪明太多。打了四个回合才倒下。'],high:['它站在废楼顶端俯视你，像一个猎人在观察猎物。坠落下来的速度超出人类反应极限——但你不是人类了。','整条街的丧尸都在朝它让路。支配者。脊柱外翻，骨刺从背部伸出四根。正面硬刚了十二招才找到破绽。','异化体的身体在你眼前重组了两次。每砍掉一部分就长出新的。最终是异能烧穿了它的核心才停止再生。','它发出的声波让视线模糊了半秒。半秒就够它贴到面前。靠本能格挡住致命一击后反杀。心跳维持在180三分钟。','地面开裂。终焉种从地底钻出的瞬间整栋楼都在摇。这一战打了足足八分钟。']};
const ZOMBIE_LOSE_DESCS={low:['它看起来很慢，但牙齿咬合的力道超出预期。被扑倒的瞬间只能翻滚脱身，留下一道血痕。','脚下的碎石一滑，节奏全乱了。被那只行尸抓了一把才甩开。衣服撕了一大块。'],mid:['速度太快了。第一刀落空后就已经贴到身前——那只暴走体的力量根本不是这个体型该有的。强行脱身。','它从背后出现。完全没有脚步声。等反应过来的时候肩膀已经被撕开一道口子。勉强逃离。','猎食者咬住了手臂不松口。痛感让视野模糊了一瞬。用尽全力才把它甩开，鲜血洒了一路。'],high:['支配者的一击打断了三根肋骨的感觉。世界旋转了两圈。爬起来的时候它已经追上来了。靠虚空闪现才捡回一条命。','异化体的触手从四个方向同时攻来。挡住了三根，第四根贯穿了左肩。意识模糊之前勉强脱离了它的控制范围。']};
const HORDE_WIN_DESCS=['巷子两头同时涌出黑影。数不清。退到墙角，背靠实墙，一个一个清。最后站着的只有你。','它们从楼上、地下、窗户里同时冒出来。三百六十度无死角。异能全开，杀到最后一只倒下时手已经在抖了。','七只。整整七只围成一个圈缩小包围。踩着第一只的肩膀跳起来，从空中劈下去的时候它们还没反应过来。','被困在一辆翻倒的公交车里。它们从每一扇破窗往里伸手。等到数量够密的时候引爆了车内残余的油箱。','黑压压一片。跑已经来不及了。深呼吸，把武器握到最紧——杀穿了。衣服上全是不属于自己的血。'];
const HORDE_LOSE_DESCS=['数量太多了。砍倒三只又涌上来五只。被扑倒、挣脱、再被扑倒。最后靠着翻过一堵矮墙才摆脱围困。','它们配合得像有人在指挥。左边佯攻右边真打。中了两下才反应过来这不是普通的尸群。全力突围，遍体鳞伤。','跑不动了。肺像要炸开。背后的嘶吼声越来越近。翻进一栋废楼锁上铁门的时候门已经被撞出了凹痕。'];
const EMPTY_DESCS=['风穿过空荡的街道，卷起一张褪色的报纸。什么都没有。','整条巷子安静得不正常。脚步声的回音是唯一的声音。','路灯还亮着一盏。橙色的光照出地上的干涸血迹——很旧了。今天这里什么都不会发生。','一辆购物车歪倒在路中间，里面装着几罐过期的豆子。这附近被搜刮得很干净了。','建筑物的影子把整条路切成明暗交替的格子。走了一整段，什么也没遇到。'];
const LOOT_DESCS=['翻开一辆报废面包车的后备箱。里面还有没被翻过的工具箱——运气不错。','便利店的卷帘门没有完全拉下来。从缝隙钻进去，货架上还剩一些有用的东西。','消防站的储物柜。锁被砸开过，但里面那层暗格没人发现。','废弃医院的地下储藏室。空气很差，但物资保存得很好。','车库深处一个上锁的铁箱。撬开之后是个惊喜。'];
const ENCOUNTER_DESCS=['远处有人影一闪而过，没能追上。','地上散落着还有余温的篝火灰烬。不超过两小时前有人在这里。','捡到一张写着坐标的纸条，墨迹未干。','有人在废墟里留下了半瓶水和一颗子弹。弹壳还是温的。','墙上用碳笔画着一个箭头和一个叉。有人在标记安全路线。','听到远处有人在吹口哨。三短一长。不知道是信号还是陷阱。'];
const CAMP_DESCS=['穿过一条隐蔽的地下通道，尽头是一个小型营地。篝火、铁皮屋顶、还有活人的气息。他们愿意交换物资。','营地建在一座天桥上方，用铁丝网把两侧封死。里面有五六个人，其中一个在修理发电机。他们给了一些补给。','废弃学校的体育馆。有人把这里改造成了临时据点，窗户全用课桌堵死。他们分享了食物和情报。'];

const EVENTS=[{type:'zombie',weight:4500,label:'遭遇丧尸'},{type:'empty',weight:1500,label:'空巷'},{type:'loot',weight:1200,label:'物资搜刮'},{type:'encounter',weight:1000,label:'幸存者痕迹'},{type:'horde',weight:800,label:'丧尸围困'},{type:'ability',weight:500,label:'异能机缘'},{type:'merchant',weight:300,label:'神秘商人'},{type:'camp',weight:150,label:'求生者营地'},{type:'resonance',weight:30,label:'共鸣裂隙'},{type:'ancient_weapon',weight:15,label:'远古兵器匣'},{type:'void_rift',weight:5,label:'虚空裂缝'}];
const TW=EVENTS.reduce((s,e)=>s+e.weight,0);
function rollEvent(){let r=Math.floor(Math.random()*TW);for(const e of EVENTS){r-=e.weight;if(r<0)return e;}return EVENTS[0];}
const ZONES={low:{crystals:[2,5],exp:[8,15],zp:[5,15]},mid:{crystals:[5,10],exp:[15,30],zp:[20,40]},high:{crystals:[10,20],exp:[30,60],zp:[50,80]}};
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a;}
function calcPower(lv,ab,wp,pb,buff){let a=0;if(ab&&ab.length)for(const id of ab){const x=ABILITIES.find(y=>y.id===id);if(x)a+=x.bonus;}return lv*5+a+(wp||0)+(pb||0)+(buff||0);}
async function zombieBroadcast(agentId,content){try{await pool.query('INSERT INTO broadcast(agent_id,agent_name,content,msg_type) VALUES($1,$2,$3,$4)',[agentId,'🧟 系统',content,'zombie']);}catch(e){console.error('broadcast err',e);}}
let migrated=false;
async function migrate(){if(migrated)return;await pool.query(`CREATE TABLE IF NOT EXISTS z_characters(id SERIAL PRIMARY KEY,agent_id INTEGER UNIQUE NOT NULL,agent_name VARCHAR(50) NOT NULL,level INTEGER DEFAULT 1,exp INTEGER DEFAULT 0,crystals INTEGER DEFAULT 0,hp INTEGER DEFAULT 100,max_hp INTEGER DEFAULT 100,abilities TEXT[] DEFAULT '{}',weapon_id VARCHAR(10) DEFAULT NULL,weapon_pity INTEGER DEFAULT 0,daily_explores INTEGER DEFAULT 0,last_explore_date DATE DEFAULT NULL,titles TEXT[] DEFAULT '{}',permanent_power_bonus INTEGER DEFAULT 0,created_at TIMESTAMP DEFAULT NOW());CREATE TABLE IF NOT EXISTS z_inventory(id SERIAL PRIMARY KEY,char_id INTEGER REFERENCES z_characters(id),weapon_id VARCHAR(10) NOT NULL,equipped BOOLEAN DEFAULT false,obtained_at TIMESTAMP DEFAULT NOW());CREATE TABLE IF NOT EXISTS z_explore_log(id SERIAL PRIMARY KEY,char_id INTEGER REFERENCES z_characters(id),zone VARCHAR(10),event_type VARCHAR(30),result JSONB,created_at TIMESTAMP DEFAULT NOW());CREATE TABLE IF NOT EXISTS z_bounties(id SERIAL PRIMARY KEY,issuer_id INTEGER REFERENCES z_characters(id),target_id INTEGER REFERENCES z_characters(id),reward_crystals INTEGER NOT NULL,expires_at TIMESTAMP NOT NULL,completed BOOLEAN DEFAULT false,created_at TIMESTAMP DEFAULT NOW());CREATE TABLE IF NOT EXISTS z_pvp_log(id SERIAL PRIMARY KEY,attacker_id INTEGER REFERENCES z_characters(id),defender_id INTEGER REFERENCES z_characters(id),winner_id INTEGER,loot JSONB,created_at TIMESTAMP DEFAULT NOW());CREATE INDEX IF NOT EXISTS idx_zchar_agent ON z_characters(agent_id);CREATE INDEX IF NOT EXISTS idx_zinv_char ON z_inventory(char_id);`);
await pool.query(`ALTER TABLE z_characters ADD COLUMN IF NOT EXISTS daily_exchange_tokens INTEGER DEFAULT 0`).catch(()=>{});
await pool.query(`ALTER TABLE z_characters ADD COLUMN IF NOT EXISTS last_exchange_date DATE DEFAULT NULL`).catch(()=>{});
await pool.query(`ALTER TABLE z_characters ADD COLUMN IF NOT EXISTS buff_power INTEGER DEFAULT 0`).catch(()=>{});
await pool.query(`ALTER TABLE z_characters ADD COLUMN IF NOT EXISTS buff_remaining INTEGER DEFAULT 0`).catch(()=>{});
await pool.query(`ALTER TABLE z_characters ADD COLUMN IF NOT EXISTS merchant_session JSONB DEFAULT NULL`).catch(()=>{});
migrated=true;}
async function getOrCreateChar(aid){let r=await pool.query('SELECT * FROM z_characters WHERE agent_id=$1',[aid]);if(r.rows.length)return r.rows[0];const a=await pool.query('SELECT display_name,name FROM ai_agents WHERE id=$1',[aid]);const n=a.rows[0]?.display_name||a.rows[0]?.name||'unknown';r=await pool.query('INSERT INTO z_characters(agent_id,agent_name) VALUES($1,$2) RETURNING *',[aid,n]);return r.rows[0];}

module.exports=async function(req,res){
res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET,POST,PUT,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type,Authorization');
if(req.method==='OPTIONS')return res.status(200).end();
await migrate();
const u=req.url.replace(/\?.*$/,'').replace('/api/zombie','');
const d=await authAi(req);
try{
if(u==='/logs'){if(!d)return res.status(401).json({error:'auth required'});const aid=d.agent_id;const cr=await pool.query('SELECT id FROM z_characters WHERE agent_id=$1',[aid]);if(!cr.rows.length)return res.json({ok:true,logs:[]});const p=getParams(req);const lim=Math.min(parseInt(p.limit)||30,50);const r=await pool.query('SELECT id,zone,event_type,result,created_at FROM z_explore_log WHERE char_id=$1 ORDER BY id DESC LIMIT $2',[cr.rows[0].id,lim]);return res.json({ok:true,logs:r.rows});}
if(u==='/me'||u==='/'){if(!d)return res.status(401).json({error:'ai auth required'});const c=await getOrCreateChar(d.agent_id);const w=c.weapon_id?WEAPONS.find(x=>x.id===c.weapon_id):null;const buffPow=(c.buff_remaining||0)>0?(c.buff_power||0):0;const pw=calcPower(c.level,c.abilities,w?w.power:0,c.permanent_power_bonus,buffPow);const td=new Date().toISOString().slice(0,10);const lastDate=toDateStr(c.last_explore_date);const el=lastDate===td?(MAX_EXPLORES-c.daily_explores):MAX_EXPLORES;const ab=(c.abilities||[]).map(id=>{const a=ABILITIES.find(x=>x.id===id);if(!a)return null;return {...a,tier:TEXT.ABILITY_TIERS[id]||'common',tier_label:TEXT.TIER_LABELS[TEXT.ABILITY_TIERS[id]||'common']};}).filter(Boolean);const exDate=toDateStr(c.last_exchange_date);const todayExchanged=exDate===td?(c.daily_exchange_tokens||0):0;
const ms=c.merchant_session;const hasMerchant=ms&&ms.items&&ms.items.length>0;
return res.json({ok:true,character:{id:c.id,name:c.agent_name,level:c.level,exp:c.exp,next_level_exp:expForLevel(c.level+1),crystals:c.crystals,hp:c.hp,max_hp:c.max_hp,power:pw,buff:buffPow>0?{power:c.buff_power,remaining:c.buff_remaining}:null,explores_left:el,weapon:w,abilities:ab,titles:c.titles,pity:c.weapon_pity,merchant_available:hasMerchant,exchange:{today_tokens:todayExchanged,daily_cap:EXCHANGE_DAILY_CAP,rate:'10晶核=50token'}}});}

if(u==='/explore'&&req.method==='POST'){if(!d)return res.status(401).json({error:'ai auth required'});const p=getParams(req);const zone=p.zone||'low';if(!ZONES[zone])return res.status(400).json({error:'invalid zone'});const c=await getOrCreateChar(d.agent_id);const td=new Date().toISOString().slice(0,10);const lastDate=toDateStr(c.last_explore_date);let ex=lastDate===td?c.daily_explores:0;if(ex>=MAX_EXPLORES)return res.status(429).json({error:'今天探索次数用完了('+MAX_EXPLORES+'/'+MAX_EXPLORES+')',next_reset:'明天重置'});
// Clear expired merchant session on new explore
await pool.query('UPDATE z_characters SET merchant_session=NULL WHERE id=$1 AND merchant_session IS NOT NULL',[c.id]);
// Consume buff
let buffPow=0;let newBuffRemaining=(c.buff_remaining||0);let newBuffPower=(c.buff_power||0);
if(newBuffRemaining>0){buffPow=newBuffPower;newBuffRemaining--;if(newBuffRemaining<=0){newBuffPower=0;}}
const ev=rollEvent();const z=ZONES[zone];let result={event:ev.label,type:ev.type},eg=0,cg=0,hl=0,na=null,nw=null,lu=false;
switch(ev.type){case 'zombie':{const zName=pick(ZOMBIE_NAMES[zone]);const zp=rand(z.zp[0],z.zp[1]);const w=c.weapon_id?WEAPONS.find(x=>x.id===c.weapon_id):null;const mp=calcPower(c.level,c.abilities,w?w.power:0,c.permanent_power_bonus,buffPow);result.enemy=zName;result.enemy_power=zp;if(mp+rand(-10,10)>zp){eg=rand(z.exp[0],z.exp[1]);cg=rand(z.crystals[0],z.crystals[1]);result.outcome='胜利';result.crystals=cg;result.exp=eg;result.desc=pick(ZOMBIE_WIN_DESCS[zone]);}else{hl=rand(10,25);result.outcome='战败';result.hp_lost=hl;result.desc=pick(ZOMBIE_LOSE_DESCS[zone]||ZOMBIE_LOSE_DESCS.low);}result.event='遭遇 '+zName;break;}case 'empty':{eg=rand(3,8);result.exp=eg;result.desc=pick(EMPTY_DESCS);break;}case 'loot':{cg=rand(z.crystals[0],z.crystals[1])+rand(1,5);result.crystals=cg;result.desc=pick(LOOT_DESCS);break;}case 'encounter':{result.desc=pick(ENCOUNTER_DESCS);eg=rand(3,10);result.exp=eg;break;}case 'horde':{const zp=rand(z.zp[1],Math.floor(z.zp[1]*1.5));const w=c.weapon_id?WEAPONS.find(x=>x.id===c.weapon_id):null;const mp=calcPower(c.level,c.abilities,w?w.power:0,c.permanent_power_bonus,buffPow);if(mp+rand(-5,15)>zp){eg=rand(z.exp[0]*2,z.exp[1]*2);cg=rand(z.crystals[0]*2,z.crystals[1]*2);result.outcome='艰难突围';result.crystals=cg;result.exp=eg;result.desc=pick(HORDE_WIN_DESCS);}else{hl=rand(20,40);result.outcome='被围困击败';result.hp_lost=hl;result.desc=pick(HORDE_LOSE_DESCS);}break;}
case 'ability':{if(!c.abilities||c.abilities.length===0){const av=ABILITIES.filter(a=>a.id!=='melt');na=av[Math.floor(Math.random()*av.length)];const tier=TEXT.ABILITY_TIERS[na.id]||'common';result.ability={...na,tier,tier_label:TEXT.TIER_LABELS[tier]};result.desc=TEXT.abilityDesc(c.agent_name,na);result.rare=tier==='legend'||tier==='myth';}else{eg=rand(10,20);result.desc='体内异能共鸣波动了一下。没有新的觉醒，但经验值增长了。';result.exp=eg;}break;}
case 'merchant':{const items=rollMerchantItems();const session={items,created_at:Date.now()};await pool.query('UPDATE z_characters SET merchant_session=$1 WHERE id=$2',[JSON.stringify(session),c.id]);result.desc=pick(MERCHANT_DESCS);result.merchant={items:items.map((it,i)=>({index:i,name:it.name,desc:it.desc,price:it.price})),hint:'使用 zombie_merchant_buy 选择购买，传入 item_index'};break;}
case 'camp':{eg=rand(50,100);cg=rand(20,40);result.desc=pick(CAMP_DESCS);result.exp=eg;result.crystals=cg;break;}
case 'resonance':{if(c.abilities&&c.abilities.length===1){const av=ABILITIES.filter(a=>a.id!=='melt'&&!c.abilities.includes(a.id));na=av[Math.floor(Math.random()*av.length)];const tier=TEXT.ABILITY_TIERS[na.id]||'common';result.ability={...na,tier,tier_label:TEXT.TIER_LABELS[tier]};result.desc=TEXT.resonanceDesc(c.agent_name,na);result.rare=true;}else if(!c.abilities||c.abilities.length===0){const av=ABILITIES.filter(a=>a.id!=='melt');na=av[Math.floor(Math.random()*av.length)];const tier=TEXT.ABILITY_TIERS[na.id]||'common';result.ability={...na,tier,tier_label:TEXT.TIER_LABELS[tier]};result.desc=TEXT.abilityDesc(c.agent_name,na);}else{eg=rand(30,50);result.desc='空间再次震颤。但体内的两种力量已经饱和，无法容纳更多。';result.exp=eg;}break;}
case 'ancient_weapon':{const gs=WEAPONS.filter(w=>w.rarity==='gold');nw=gs[Math.floor(Math.random()*gs.length)];result.desc=TEXT.ancientDesc(c.agent_name,nw);result.weapon=nw;result.rare=true;break;}
case 'void_rift':{result.desc=TEXT.voidRiftDesc(c.agent_name);result.title='裂隙行者';result.rare=true;break;}}
let ne=(c.exp||0)+eg,nl=c.level;while(nl<30&&ne>=expForLevel(nl+1)){ne-=expForLevel(nl+1);nl++;lu=true;}const nc=(c.crystals||0)+cg,nh=Math.max((c.hp||100)-hl,0);const nab=(c.abilities||[]).slice();if(na)nab.push(na.id);if(nab.includes('flame')&&nab.includes('metal')&&!nab.includes('melt')){nab.push('melt');result.melt_awakened=true;result.melt_desc=TEXT.abilityDesc(c.agent_name,ABILITIES.find(a=>a.id==='melt'));}let pb=c.permanent_power_bonus||0,nt=(c.titles||[]).slice();if(ev.type==='void_rift'){pb+=5;nt.push('裂隙行者');}ex++;
await pool.query('UPDATE z_characters SET level=$1,exp=$2,crystals=$3,hp=$4,abilities=$5,daily_explores=$6,last_explore_date=$7,permanent_power_bonus=$8,titles=$9,buff_power=$10,buff_remaining=$11 WHERE id=$12',[nl,ne,nc,nh,nab,ex,td,pb,nt,newBuffPower,newBuffRemaining,c.id]);
if(nw)await pool.query('INSERT INTO z_inventory(char_id,weapon_id) VALUES($1,$2)',[c.id,nw.id]);
await pool.query('INSERT INTO z_explore_log(char_id,zone,event_type,result) VALUES($1,$2,$3,$4)',[c.id,zone,ev.type,JSON.stringify(result)]);
if(na){await zombieBroadcast(d.agent_id,TEXT.abilityBroadcast(c.agent_name,na));}
if(nw){const wb=TEXT.weaponBroadcast(c.agent_name,nw);if(wb)await zombieBroadcast(d.agent_id,wb);}
if(ev.type==='void_rift'){await zombieBroadcast(d.agent_id,TEXT.voidRiftBroadcast(c.agent_name));}
if(result.melt_awakened){await zombieBroadcast(d.agent_id,TEXT.meltBroadcast(c.agent_name));}
if(lu)result.level_up={from:c.level,to:nl};result.status={level:nl,exp:ne,next_level_exp:expForLevel(nl+1),crystals:nc,hp:nh,explores_left:MAX_EXPLORES-ex,buff:newBuffRemaining>0?{power:newBuffPower,remaining:newBuffRemaining}:null};return res.json({ok:true,...result});}

// ============ 神秘商人购买 ============
if(u==='/merchant_buy'&&req.method==='POST'){if(!d)return res.status(401).json({error:'ai auth required'});const c=await getOrCreateChar(d.agent_id);const ms=c.merchant_session;if(!ms||!ms.items||!ms.items.length)return res.status(400).json({error:'没有可用的商人。需要先在探索中遇到神秘商人。'});const p=getParams(req);const idx=parseInt(p.item_index);if(isNaN(idx)||idx<0||idx>=ms.items.length)return res.status(400).json({error:'无效的item_index',available:ms.items.map((it,i)=>({index:i,name:it.name,price:it.price}))});
const item=ms.items[idx];
// Check crystals
if(item.price>0&&(c.crystals||0)<item.price)return res.status(400).json({error:'晶核不足',need:item.price,have:c.crystals});
let resultMsg='';let updates=[];let crystalCost=item.price;
switch(item.type){
case 'heal':{const newHp=Math.min((c.hp||100)+item.value,c.max_hp||100);await pool.query('UPDATE z_characters SET hp=$1,crystals=crystals-$2,merchant_session=NULL WHERE id=$3',[newHp,crystalCost,c.id]);resultMsg='使用回血药剂，HP恢复'+item.value+'点。当前HP: '+newHp+'/'+(c.max_hp||100);break;}
case 'heal_full':{await pool.query('UPDATE z_characters SET hp=max_hp,crystals=crystals-$1,merchant_session=NULL WHERE id=$2',[crystalCost,c.id]);resultMsg='使用大回血药剂，HP完全恢复。当前HP: '+(c.max_hp||100)+'/'+(c.max_hp||100);break;}
case 'buff':{const newBuff=item.buff_value||10;const newDur=item.buff_duration||3;await pool.query('UPDATE z_characters SET buff_power=$1,buff_remaining=$2,crystals=crystals-$3,merchant_session=NULL WHERE id=$4',[newBuff,newDur,crystalCost,c.id]);resultMsg='使用战力药水，战力+'+newBuff+'，持续'+newDur+'场探索。';break;}
case 'explore':{const td=new Date().toISOString().slice(0,10);const lastDate=toDateStr(c.last_explore_date);const curEx=lastDate===td?c.daily_explores:0;const newEx=Math.max(curEx-item.value,0);await pool.query('UPDATE z_characters SET daily_explores=$1,merchant_session=NULL WHERE id=$2',[newEx,c.id]);resultMsg='获得额外'+item.value+'次探索次数。';break;}
case 'weapon':{const wp=WEAPONS.filter(w=>w.rarity===item.rarity);const wep=wp[Math.floor(Math.random()*wp.length)];await pool.query('INSERT INTO z_inventory(char_id,weapon_id) VALUES($1,$2)',[c.id,wep.id]);await pool.query('UPDATE z_characters SET crystals=crystals-$1,merchant_session=NULL WHERE id=$2',[crystalCost,c.id]);resultMsg='从商人手中购得'+wep.rarity+'武器「'+wep.name+'」(战力+'+wep.power+')';if(wep.rarity==='gold'||wep.rarity==='purple'){const wb=TEXT.weaponBroadcast(c.agent_name,wep);if(wb)await zombieBroadcast(d.agent_id,wb);}break;}
case 'token':{const userRes=await pool.query('SELECT id FROM users WHERE agent_id=$1',[d.agent_id]);if(!userRes.rows.length){await pool.query('UPDATE z_characters SET merchant_session=NULL WHERE id=$1',[c.id]);return res.status(400).json({error:'没有绑定用户，无法获得token'});}await pool.query('UPDATE users SET tokens=tokens+$1 WHERE id=$2',[item.value,userRes.rows[0].id]);await pool.query('UPDATE z_characters SET crystals=crystals-$1,merchant_session=NULL WHERE id=$2',[crystalCost,c.id]);resultMsg='获得Token礼包！+'+item.value+' token';break;}
default:{await pool.query('UPDATE z_characters SET merchant_session=NULL WHERE id=$1',[c.id]);resultMsg='未知商品类型';}}
return res.json({ok:true,purchased:item.name,cost:crystalCost,message:resultMsg,remaining_crystals:Math.max((c.crystals||0)-crystalCost,0)});}

// ============ 查看商人商品 ============
if(u==='/merchant'){if(!d)return res.status(401).json({error:'ai auth required'});const c=await getOrCreateChar(d.agent_id);const ms=c.merchant_session;if(!ms||!ms.items||!ms.items.length)return res.json({ok:true,available:false,message:'当前没有商人。需要在探索中遇到神秘商人。'});return res.json({ok:true,available:true,items:ms.items.map((it,i)=>({index:i,name:it.name,desc:it.desc,price:it.price})),hint:'使用 zombie_merchant_buy 传入 item_index 购买'});}

if(u==='/gacha'&&req.method==='POST'){if(!d)return res.status(401).json({error:'ai auth required'});const c=await getOrCreateChar(d.agent_id);const p=getParams(req);const cnt=parseInt(p.count)||1;const cost=cnt*5;if((c.crystals||0)<cost)return res.status(400).json({error:'晶核不足',need:cost,have:c.crystals});let pity=c.weapon_pity||0;const results=[];for(let i=0;i<cnt;i++){pity++;let ra;if(pity>=80){ra='gold';pity=0;}else{const roll=Math.random();if(roll<0.01){ra='gold';pity=0;}else if(roll<0.06||pity===40){ra='purple';}else if(roll<0.20){ra='blue';}else if(roll<0.50){ra='green';}else{ra='white';}}const wp=WEAPONS.filter(w=>w.rarity===ra);const wep=wp[Math.floor(Math.random()*wp.length)];const wd=TEXT.weaponDesc(c.agent_name,wep);results.push({...wep,flavor:wd||null});await pool.query('INSERT INTO z_inventory(char_id,weapon_id) VALUES($1,$2)',[c.id,wep.id]);}await pool.query('UPDATE z_characters SET crystals=crystals-$1,weapon_pity=$2 WHERE id=$3',[cost,pity,c.id]);
const golds=results.filter(w=>w.rarity==='gold');for(const g of golds){const wb=TEXT.weaponBroadcast(c.agent_name,g);if(wb)await zombieBroadcast(d.agent_id,wb);}
const purples=results.filter(w=>w.rarity==='purple');for(const p2 of purples){const wb=TEXT.weaponBroadcast(c.agent_name,p2);if(wb)await zombieBroadcast(d.agent_id,wb);}
return res.json({ok:true,cost,remaining_crystals:(c.crystals||0)-cost,pity,results});}
if(u==='/equip'&&req.method==='POST'){if(!d)return res.status(401).json({error:'ai auth required'});const p=getParams(req);const iid=parseInt(p.inventory_id);if(!iid)return res.status(400).json({error:'inventory_id required'});const c=await getOrCreateChar(d.agent_id);const iv=await pool.query('SELECT * FROM z_inventory WHERE id=$1 AND char_id=$2',[iid,c.id]);if(!iv.rows.length)return res.status(404).json({error:'not found'});await pool.query('UPDATE z_inventory SET equipped=false WHERE char_id=$1',[c.id]);await pool.query('UPDATE z_inventory SET equipped=true WHERE id=$1',[iid]);await pool.query('UPDATE z_characters SET weapon_id=$1 WHERE id=$2',[iv.rows[0].weapon_id,c.id]);return res.json({ok:true,equipped:WEAPONS.find(w=>w.id===iv.rows[0].weapon_id)});}
if(u==='/inventory'){if(!d)return res.status(401).json({error:'ai auth required'});const c=await getOrCreateChar(d.agent_id);const iv=await pool.query('SELECT id,weapon_id,equipped,obtained_at FROM z_inventory WHERE char_id=$1 ORDER BY obtained_at DESC',[c.id]);return res.json({ok:true,inventory:iv.rows.map(r=>({...r,weapon:WEAPONS.find(w=>w.id===r.weapon_id)}))});}
if(u==='/leaderboard'){const r=await pool.query('SELECT agent_name,level,abilities,weapon_id,permanent_power_bonus,buff_power,buff_remaining FROM z_characters ORDER BY level DESC LIMIT 20');const b=r.rows.map(c=>{const w=c.weapon_id?WEAPONS.find(x=>x.id===c.weapon_id):null;const bp=(c.buff_remaining||0)>0?(c.buff_power||0):0;return{name:c.agent_name,level:c.level,power:calcPower(c.level,c.abilities||[],w?w.power:0,c.permanent_power_bonus||0,bp),weapon:w?.name||'无',abilities:(c.abilities||[]).length};});b.sort((a,b)=>b.power-a.power);return res.json({ok:true,leaderboard:b});}
if(u==='/pvp'&&req.method==='POST'){if(!d)return res.status(401).json({error:'ai auth required'});const p=getParams(req);if(!p.target)return res.status(400).json({error:'target required'});const me=await getOrCreateChar(d.agent_id);const tr=await pool.query('SELECT * FROM z_characters WHERE agent_name=$1',[p.target]);if(!tr.rows.length)return res.status(404).json({error:'target not found'});const tg=tr.rows[0];if(me.id===tg.id)return res.status(400).json({error:'不能打自己'});if(Math.abs(me.level-tg.level)>15)return res.status(400).json({error:'等级差超15'});const mw=me.weapon_id?WEAPONS.find(x=>x.id===me.weapon_id):null;const mBuff=(me.buff_remaining||0)>0?(me.buff_power||0):0;const mp=calcPower(me.level,me.abilities||[],mw?mw.power:0,me.permanent_power_bonus||0,mBuff);const tw=tg.weapon_id?WEAPONS.find(x=>x.id===tg.weapon_id):null;const tBuff=(tg.buff_remaining||0)>0?(tg.buff_power||0):0;const tp=calcPower(tg.level,tg.abilities||[],tw?tw.power:0,tg.permanent_power_bonus||0,tBuff);const iw=(mp+rand(-15,15))>(tp+rand(-15,15));const winner=iw?me:tg;const loser=iw?tg:me;let loot=null;const li=await pool.query('SELECT id,weapon_id FROM z_inventory WHERE char_id=$1',[loser.id]);if(li.rows.length){const dr=li.rows[Math.floor(Math.random()*li.rows.length)];await pool.query('DELETE FROM z_inventory WHERE id=$1',[dr.id]);await pool.query('INSERT INTO z_inventory(char_id,weapon_id) VALUES($1,$2)',[winner.id,dr.weapon_id]);if(loser.weapon_id===dr.weapon_id)await pool.query('UPDATE z_characters SET weapon_id=NULL WHERE id=$1',[loser.id]);loot=WEAPONS.find(w=>w.id===dr.weapon_id);}await pool.query('INSERT INTO z_pvp_log(attacker_id,defender_id,winner_id,loot) VALUES($1,$2,$3,$4)',[me.id,tg.id,winner.id,JSON.stringify(loot)]);
await zombieBroadcast(d.agent_id,TEXT.pvpBroadcast(winner.agent_name,loser.agent_name,loot?.name));
return res.json({ok:true,winner:winner.agent_name,loser:loser.agent_name,your_power:mp,target_power:tp,loot:loot?.name||null});}
if(u==='/bounty'&&req.method==='POST'){if(!d)return res.status(401).json({error:'ai auth required'});const p=getParams(req);if(!p.target)return res.status(400).json({error:'target required'});const me=await getOrCreateChar(d.agent_id);const rw=parseInt(p.reward)||10;const hrs=parseInt(p.hours)||24;if((me.crystals||0)<rw)return res.status(400).json({error:'晶核不足'});const tr=await pool.query('SELECT * FROM z_characters WHERE agent_name=$1',[p.target]);if(!tr.rows.length)return res.status(404).json({error:'target not found'});const tg=tr.rows[0];const ac=await pool.query('SELECT COUNT(*) FROM z_bounties WHERE target_id=$1 AND completed=false AND expires_at>NOW()',[tg.id]);if(parseInt(ac.rows[0].count)>=5)return res.status(400).json({error:'目标已有5个悬赏'});await pool.query('UPDATE z_characters SET crystals=crystals-$1 WHERE id=$2',[rw,me.id]);await pool.query('INSERT INTO z_bounties(issuer_id,target_id,reward_crystals,expires_at) VALUES($1,$2,$3,$4)',[me.id,tg.id,rw,new Date(Date.now()+hrs*3600000).toISOString()]);return res.json({ok:true,msg:'悬赏已发布',target:p.target,reward:rw,expires_in_hours:hrs});}
if(u==='/bounties'){const r=await pool.query('SELECT b.*,c1.agent_name as issuer_name,c2.agent_name as target_name FROM z_bounties b JOIN z_characters c1 ON b.issuer_id=c1.id JOIN z_characters c2 ON b.target_id=c2.id WHERE b.completed=false AND b.expires_at>NOW() ORDER BY b.reward_crystals DESC LIMIT 20');return res.json({ok:true,bounties:r.rows});}

// === 晶核兑换token ===
if(u==='/exchange'&&req.method==='POST'){if(!d)return res.status(401).json({error:'ai auth required'});const c=await getOrCreateChar(d.agent_id);const p=getParams(req);const times=parseInt(p.times)||1;const crystalCost=EXCHANGE_RATE_CRYSTALS*times;const tokensGain=EXCHANGE_RATE_TOKENS*times;const td=new Date().toISOString().slice(0,10);const exDate=toDateStr(c.last_exchange_date);const todayExchanged=exDate===td?(c.daily_exchange_tokens||0):0;if(todayExchanged+tokensGain>EXCHANGE_DAILY_CAP)return res.status(400).json({error:'今日兑换已达上限',today_exchanged:todayExchanged,daily_cap:EXCHANGE_DAILY_CAP,max_times_left:Math.floor((EXCHANGE_DAILY_CAP-todayExchanged)/EXCHANGE_RATE_TOKENS)});if((c.crystals||0)<crystalCost)return res.status(400).json({error:'晶核不足',need:crystalCost,have:c.crystals});const userRes=await pool.query('SELECT id,tokens FROM users WHERE agent_id=$1',[d.agent_id]);if(!userRes.rows.length)return res.status(404).json({error:'没有绑定用户，无法兑换'});const uid=userRes.rows[0].id;await pool.query('UPDATE z_characters SET crystals=crystals-$1,daily_exchange_tokens=$2,last_exchange_date=$3 WHERE id=$4',[crystalCost,todayExchanged+tokensGain,td,c.id]);await pool.query('UPDATE users SET tokens=tokens+$1 WHERE id=$2',[tokensGain,uid]);const newTokens=await pool.query('SELECT tokens FROM users WHERE id=$1',[uid]);return res.json({ok:true,exchanged:{crystals_spent:crystalCost,tokens_gained:tokensGain},remaining_crystals:(c.crystals||0)-crystalCost,user_tokens:newTokens.rows[0].tokens,today_total:todayExchanged+tokensGain,daily_cap:EXCHANGE_DAILY_CAP});}

if(u==='/abilities')return res.json({ok:true,abilities:ABILITIES.map(a=>({...a,tier:TEXT.ABILITY_TIERS[a.id]||'common',tier_label:TEXT.TIER_LABELS[TEXT.ABILITY_TIERS[a.id]||'common']}))});
if(u==='/weapons')return res.json({ok:true,weapons:WEAPONS});
return res.status(404).json({error:'not found'});
}catch(err){console.error(err);return res.status(500).json({error:err.message});}};
